INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, invited_at, confirmation_token, confirmation_sent_at, recovery_token, recovery_sent_at, email_change_token_new, email_change, email_change_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, created_at, updated_at, phone, phone_confirmed_at, phone_change, phone_change_token, phone_change_sent_at, email_change_token_current, email_change_confirm_status, banned_until, reauthentication_token, reauthentication_sent_at, is_sso_user, deleted_at, is_anonymous)
VALUES
('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'admin@gmail.com', '$2a$12$QH0P5OX1JFle0x.FZBDX9OSXFfzBfxvVi.mysnHipRMGWHG82XAku', now(), null, '', null, '', null, '', '', null, null, '{"provider": "email", "providers": ["email"]}', '{}', null, now(), now(), null, null, '', '', null, '', 0, null, '', null, false, null, false),
-- ('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'user@gmail.com', '$2a$10$Lo9cAODelKJneK2W6EN3Ku27aCy0m1ZvD5jFbINRaSV2U29Elsalq', now(), null, '', null, '', null, '', '', null, null, '{"provider": "email", "providers": ["email"]}', '{}', null, now(), now(), null, null, '', '', null, '', 0, null, '', null, false, null, false),
-- ('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'circle_member@gmail.com', '$2a$10$Lo9cAODelKJneK2W6EN3Ku27aCy0m1ZvD5jFbINRaSV2U29Elsalq', now(), null, '', null, '', null, '', '', null, null, '{"provider": "email", "providers": ["email"]}', '{}', null, now(), now(), null, null, '', '', null, '', 0, null, '', null, false, null, false),
-- ('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'follower@gmail.com', '$2a$10$Lo9cAODelKJneK2W6EN3Ku27aCy0m1ZvD5jFbINRaSV2U29Elsalq', now(), null, '', null, '', null, '', '', null, null, '{"provider": "email", "providers": ["email"]}', '{}', null, now(), now(), null, null, '', '', null, '', 0, null, '', null, false, null, false),
('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'dev.khoanguyen79@gmail.com', '$2a$12$I.AiwAAP.kywZTmn4Ip45uAEHNeWZGXb7wvoXehdyki1xuam.7mGS', now(), null, '', null, '', null, '', '', null, null, '{"provider": "email", "providers": ["email"]}', '{}', null, now(), now(), null, null, '', '', null, '', 0, null, '', null, false, null, false);

-- INSERT INTO public.categories (id, title, logo, description, created_at) VALUES (1, 'Design', '', 'Design courses', now());

-- INSERT INTO courses (id, user_id, category_id, banner, title, cost, sale_price, description, duration, discount, has_access_all_device, has_certidication, has_money_back_guarantee, created_at)
-- VALUES
-- (1, (SELECT id FROM auth.users WHERE email = 'dev.khoanguyen79@gmail.com'), (SELECT id FROM public.categories WHERE title = 'Design'), '', 'Design course 1', 100, 50, 'Design course 1 description', 10, 0, TRUE, TRUE, TRUE, now());