import '@/shared/styles/globals.style.css'

import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import { Toaster } from '@/components/ui/toaster'
import AppProvider from '@/context/AppProvider'
import ReactQueryProvider from '@/providers/ReactQueryProvider'
import { cookieStoreServer } from '@/shared/utils/cookies/server.util'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const token = cookieStoreServer.get('accessToken')
  return (
    <html lang='en'>
      <body className={poppins.className} suppressHydrationWarning>
        <ReactQueryProvider>
          <AppProvider initialSessionToken={token?.value ?? ''}>
            {children}
            <Toaster />
          </AppProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
