CREATE TABLE public.users(
    id uuid PRIMARY KEY,
    name VARCHAR(255),
    avatar VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE
);

CREATE TABLE public.categories(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    logo VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE
);

CREATE TABLE public.courses(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users NOT NULL,
    category_id BIGINT REFERENCES public.categories NOT NULL,
    title VARCHAR(255) NOT NULL,
    cost FLOAT(53) NOT NULL,
    sale_price FLOAT(53) NOT NULL,
    description TEXT NOT NULL,
    banner VARCHAR(255),
    duration int,
    discount FLOAT(53),
    has_access_all_device BOOLEAN DEFAULT TRUE,
    has_certification BOOLEAN DEFAULT TRUE,
    has_money_back_guarantee BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE
);

CREATE TABLE public.blogs(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.users NOT NULL,
    category_id BIGINT REFERENCES public.categories NOT NULL,
    logo VARCHAR(255),
    title TEXT,
    description TEXT,
    content TEXT,
    view BIGINT,
    tags JSON,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE
);

CREATE TABLE public.reviews(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.users NOT NULL,
    course_id BIGINT REFERENCES public.courses NOT NULL,
    rating int NOT NULL,
    comment VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE
);

CREATE TABLE public.orders(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    course_id BIGINT REFERENCES public.courses NOT NULL,
    user_id uuid REFERENCES public.users NOT NULL,
    total FLOAT(53) NOT NULL,
    status int NOT NULL,
    payment_method VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE,
    update_at TIMESTAMP(0) WITHOUT TIME ZONE
);

CREATE TABLE public.order_details(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders NOT NULL,
		course_id BIGINT REFERENCES public.courses NOT NULL,
    price FLOAT(53) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE
);
